version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: docker run --name=postgres -e POSTGRES_PASSWORD -d postgres 
      - run: docker build -t circle-test .
      - run: docker run -it --rm --link postgres:postgres -e DATABASE_URL=postgres://postgres:$POSTGRES_PASSWORD@postgres/postgres_test -e RAILS_ENV=test circle_test rake db:create
      - run: docker run -it --rm --link postgres:postgres -e DATABASE_URL=postgres://postgres:$POSTGRES_PASSWORD@postgres/postgres_test -e RAILS_ENV=test circle_test rake db:test:prepare
      - run: docker run -it --rm --link postgres:postgres -e DATABASE_URL=postgres://postgres:$POSTGRES_PASSWORD@postgres/postgres_test -e RAILS_ENV=test circle_test rake test
      
          
      