version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: docker run --name=postgres -e POSTGRES_PASSWORD -d postgres 
      - run: docker build -t circle-test .
      - run: docker run -it --rm --link postgres:postgres -e DATABASE_URL=postgres://postgres:$POSTGRES_PASSWORD@postgres/circle_test -e RAILS_ENV=test circle-test rake db:create db:test:prepare
#      - run: docker run -it --rm --link postgres:postgres -e DATABASE_URL=postgres://postgres:$POSTGRES_PASSWORD@postgres/circle_test -e RAILS_ENV=test circle-test rake db:test:prepare
      - run: docker run -it --rm --link postgres:postgres -e DATABASE_URL=postgres://postgres:$POSTGRES_PASSWORD@postgres/circle_test -e RAILS_ENV=test circle-test rake test
      - run: docker run -it --rm --link postgres:postgres -e DATABASE_URL=postgres://postgres:$POSTGRES_PASSWORD@postgres/circle circle-test brakeman --no-pager
      - run: docker run -it --rm --link postgres:postgres -e DATABASE_URL=postgres://postgres:$POSTGRES_PASSWORD@postgres/circle circle-test rake db:create db:schema:load
#      - run: docker run -it --rm --link postgres:postgres -e DATABASE_URL=postgres://postgres:$POSTGRES_PASSWORD@postgres/circle circle-test rake db:schema:load
#      - run: docker run -d --name=smoketest --health-interval=4s --link postgres:postgres -e DATABASE_URL=postgres://postgres:$POSTGRES_PASSWORD@postgres/circle circle-test 
#      - run: sleep 60 # ugly but gives the web app time to boot
#      - run: docker ps | grep smoketest | grep '(healthy)' || false
      
      
          
      