version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    environment:
      DATABASE_URL: postgres://postgres:$POSTGRES_PASSWORD@postgres/circle_test
      WEB_DB_URL: postgres://postgres:$POSTGRES_PASSWORD@postgres/circle
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: docker run --name=postgres -e POSTGRES_PASSWORD -d postgres 
      - run: docker build -t circle-test .
      - run: docker run -it --rm --link postgres:postgres -e DATABASE_URL -e RAILS_ENV=test circle-test rake db:create
      - run: docker run -it --rm --link postgres:postgres -e DATABASE_URL -e RAILS_ENV=test circle-test rake db:test:prepare
      - run: docker run -it --rm --link postgres:postgres -e DATABASE_URL -e RAILS_ENV=test circle-test rake test
      
          
      